environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
matrix:
  fast_finish: true
install:
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install netCDF4"
  - "%PYTHON%\\python.exe -m pip install -e ."
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest tests"
