inputs,c_in_rain;c_in_peva
outputs,c_out_aeva;c_out_q_h2o_ove;c_out_q_h2o_dra;c_out_q_h2o_int;c_out_q_h2o_sgw;c_out_q_h2o_dgw;c_out_q_h2o
states,c_s_v_h2o_ove;c_s_v_h2o_dra;c_s_v_h2o_int;c_s_v_h2o_sgw;c_s_v_h2o_dgw;c_s_v_h2o_ly1;c_s_v_h2o_ly2;c_s_v_h2o_ly3;c_s_v_h2o_ly4;c_s_v_h2o_ly5;c_s_v_h2o_ly6
parameters,c_p_t;c_p_c;c_p_h;c_p_d;c_p_s;c_p_z;c_p_sk;c_p_fk;c_p_gk
constants,
